# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='tests',
            field=models.ManyToManyField(blank=True, to='maths.Test', verbose_name='tester'),
        ),
        migrations.AddField(
            model_name='gruppe',
            name='tests',
            field=models.ManyToManyField(blank=True, to='maths.Test', verbose_name='tester'),
        ),
        migrations.AddField(
            model_name='person',
            name='tests',
            field=models.ManyToManyField(blank=True, to='maths.Test', verbose_name='tester'),
        ),
    ]
