# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maths', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='tests',
            field=models.ManyToManyField(to='maths.TestView'),
        ),
        migrations.AddField(
            model_name='person',
            name='grade',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Grade', verbose_name='klasse'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
