# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning', models.CharField(max_length=32700, null=True)),
                ('text', models.CharField(max_length=32700, null=True)),
                ('date_answered', models.DateTimeField(null=True)),
                ('timespent', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50, verbose_name='kategori')),
            ],
            options={
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='GeogebraAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.CharField(max_length=32700)),
                ('data', models.CharField(max_length=2000, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='GeogebraTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.CharField(max_length=32700)),
                ('preview', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(blank=True, max_length=32700)),
                ('answertype', models.IntegerField()),
                ('reasoning', models.BooleanField()),
                ('extra', models.BooleanField()),
                ('variables', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='maths.Category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100, verbose_name='test navn')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(to='maths.Task', verbose_name='oppgaver')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(verbose_name='Publisert')),
                ('dueDate', models.DateTimeField(blank=True, null=True, verbose_name='Siste frist for besvarelse')),
                ('randomOrder', models.BooleanField(default=False, help_text='Dersom avkrysset vil testen bli gitt i tilfeldig rekkefølge.', verbose_name='Tilfeldig rekkefølge')),
                ('strictOrder', models.BooleanField(default=False, verbose_name='Lås rekkefølge')),
                ('task_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.TaskCollection')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='taskorder',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Test'),
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Task'),
        ),
        migrations.AddField(
            model_name='item',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Task'),
        ),
        migrations.AddField(
            model_name='geogebratask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Task'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Task'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Test'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
