# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='variables',
            field=models.BooleanField(default=False),
        ),
    ]
