# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_auto_20170608_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='variables',
            new_name='variableTask',
        ),
    ]
