# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_taskcollection_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='variableDescription',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
