# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_task_variabledescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variables',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
