# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0007_auto_20170611_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='variableDescription',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
