# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0009_auto_20170612_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.Item'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.Task'),
        ),
    ]
