# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0011_remove_taskcollection_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='multiplechoicetask',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='multiplechoicetask',
            name='option',
        ),
        migrations.AddField(
            model_name='multiplechoicetask',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='MutipleChoiceTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.MultipleChoiceTask'),
        ),
    ]
