# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0012_auto_20170616_0808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoice',
            new_name='MultipleChoiceOption',
        ),
    ]
