# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maths', '0014_answer_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogitTestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logit', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Item')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Test')),
            ],
        ),
        migrations.CreateModel(
            name='LogitTestPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logit', models.FloatField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Test')),
            ],
        ),
    ]
