# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0015_logittestitem_logittestperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='random_variables',
            field=models.BooleanField(default=False),
        ),
    ]
