# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0016_item_random_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reasoningText',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
