# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0017_task_reasoningtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicetask',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
