# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0018_multiplechoicetask_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='geogebratask',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geogebratask',
            name='width',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
