# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0019_auto_20170705_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='geogebratask',
            name='enableLabelDrags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='geogebratask',
            name='enableRightClick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='geogebratask',
            name='enableShiftDragZoom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='geogebratask',
            name='showMenuBar',
            field=models.BooleanField(default=False),
        ),
    ]
