# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0020_auto_20170705_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
