# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0021_test_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcollection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
