# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0022_auto_20170707_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='task',
        ),
    ]
