# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0023_remove_answer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Item'),
        ),
    ]
