# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0024_auto_20170707_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anonymous_user',
            field=models.IntegerField(null=True),
        ),
    ]
