# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0025_answer_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geogebratask',
            name='base64',
            field=models.TextField(null=True),
        ),
    ]
