# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0027_auto_20170724_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geogebraanswer',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
