# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0028_auto_20170724_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='inputfieldtask',
            name='title',
        ),
        migrations.AddField(
            model_name='inputfieldtask',
            name='question',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='inputFieldTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.InputFieldTask'),
        ),
    ]
