# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0029_auto_20170725_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='inputnr',
            field=models.IntegerField(null=True),
        ),
    ]
