# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0030_inputfield_inputnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='correct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inputfield',
            name='inputlength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reasoning',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, max_length=15000),
        ),
    ]
