# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maths', '0036_auto_20170808_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
